max_chat_blob_buffer_token_size: 512
buffer_flush_interval: 3600

llm_api_key: ollama
llm_base_url: http://192.168.100.195:11434/v1
best_llm_model: qwen2.5:7b
embedding_model: nomic-embed-text:latest
embedding_dim: 768


language: en
